# Generated by Django 3.2.6 on 2021-08-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('reviews', '0002_auto_20210826_0917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='books', to='genres.Genre'),
        ),
    ]
