# Generated by Django 3.2.6 on 2021-08-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20210826_0932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
