# Generated by Django 3.2.6 on 2021-08-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_delete_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_posted']},
        ),
    ]
