# Generated by Django 3.2.6 on 2021-09-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Review'},
        ),
    ]
