# Generated by Django 3.2.6 on 2021-08-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('publication_year', models.IntegerField(default=2021)),
                ('cover_img', models.ImageField(default='book_covers/default.png', upload_to='book_covers')),
                ('summary', models.TextField(max_length=1028)),
                ('authors', models.ManyToManyField(blank=True, related_name='books', to='authors.Author')),
                ('genres', models.ManyToManyField(blank=True, related_name='books', to='genres.Genre')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
