# Generated by Django 3.2.6 on 2021-08-31 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210826_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title',), 'verbose_name': 'Book'},
        ),
    ]
