# Generated by Django 3.2.6 on 2021-09-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_posted',), 'verbose_name': 'Comment'},
        ),
    ]
